"""
Utility functions for the AI Code Reviewer Action.

This module provides helper functions for file filtering and pattern matching:
- Detecting self-generated files (to prevent infinite loops)
- Checking file exclusion against glob patterns
- Parsing comma-separated exclude patterns from user input
"""

import fnmatch
from typing import List


# Paths that the Action itself generates (should never be analyzed)
# This prevents infinite loops where the Action analyzes its own output files.
SELF_GENERATED_PATHS = [
    'docs/auto/',      # Directory for auto-generated documentation
    'docs/reviews/',   # Directory for review reports
]


def is_self_generated(filepath: str) -> bool:
    """
    Checks if a file was generated by this Action.

    These files should be excluded from analysis to prevent infinite loops
    where the Action analyzes its own output and generates new versions.

    Args:
        filepath (str): Path to the file (e.g., "docs/auto/DOCUMENTATION.md")

    Returns:
        bool: True if the file is in a self-generated directory, False otherwise

    Example:
        >>> is_self_generated("docs/auto/DOCUMENTATION.md")
        True
        >>> is_self_generated("src/main.py")
        False
    """
    for path in SELF_GENERATED_PATHS:
        if filepath.startswith(path):
            return True
    return False


def is_excluded(filepath: str, patterns: List[str]) -> bool:
    """
    Checks if a file should be excluded from analysis based on glob patterns.

    The function first checks if the file is self-generated (always excluded).
    Then it matches the filepath against provided glob patterns.

    Args:
        filepath (str): Path to the file (e.g., "src/main.py" or "tests/test_auth.py")
        patterns (List[str]): List of glob patterns to match against.
            Supported patterns:
            - Exact matches: "venv"
            - Wildcards: "*.log", "test_*.py"
            - Directory recursion: "tests/**", "**/*_test.py"
            - Simple directories: "docs/" (matches files inside)

    Returns:
        bool: True if file should be excluded, False otherwise

    Examples:
        >>> patterns = ["tests/**", "**/*_test.py"]
        >>> is_excluded("tests/test_auth.py", patterns)
        True
        >>> is_excluded("src/main.py", patterns)
        False
        >>> is_excluded("docs/auto/DOCUMENTATION.md", patterns)  # Self-generated
        True

    Note:
        Self-generated files (docs/auto/, docs/reviews/) are always excluded
        regardless of the provided patterns.
    """
    # Always exclude self-generated files first
    if is_self_generated(filepath):
        return True

    # No patterns = nothing to exclude
    if not patterns:
        return False

    for pattern in patterns:
        # Direct glob pattern match (supports *, **, ?)
        if fnmatch.fnmatch(filepath, pattern):
            return True

        # Handle directory recursion pattern like "tests/**"
        if pattern.endswith('/**'):
            folder = pattern[:-2]  # Remove '/**'
            if filepath.startswith(folder) or filepath.startswith(folder + '/'):
                return True

        # Handle simple directory without wildcards
        if not any(c in pattern for c in '*?['):
            if filepath.startswith(pattern + '/') or filepath == pattern:
                return True

    return False


def parse_exclude_patterns(exclude_str: str) -> List[str]:
    """
    Parses a comma-separated string of exclude patterns into a list.

    Args:
        exclude_str (str): Comma-separated patterns, e.g., "tests/**,**/*_test.py,venv/**"
            Leading/trailing whitespace is automatically stripped from each pattern.
            Empty strings are filtered out.

    Returns:
        List[str]: List of parsed patterns, or empty list if input is empty.

    Examples:
        >>> parse_exclude_patterns("tests/**,**/*_test.py")
        ['tests/**', '**/*_test.py']

        >>> parse_exclude_patterns("  venv/** , *.log  ")
        ['venv/**', '*.log']

        >>> parse_exclude_patterns("")
        []

    Note:
        This function does not validate the patterns — it only splits and cleans them.
        Pattern validation happens in is_excluded() using fnmatch.
    """
    if not exclude_str:
        return []
    # Split by comma, strip whitespace, filter out empty strings
    return [p.strip() for p in exclude_str.split(',') if p.strip()]