"""
Utility functions for the AI Code Reviewer Action.
"""

import fnmatch
from typing import List


# Paths that the Action itself generates (should never be analyzed)
SELF_GENERATED_PATHS = [
    'docs/auto/',
    'docs/reviews/',
]


def is_self_generated(filepath: str) -> bool:
    """
    Check if a file was generated by this Action.
    These files should be excluded from analysis to prevent infinite loops.
    """
    for path in SELF_GENERATED_PATHS:
        if filepath.startswith(path):
            return True
    return False


def is_excluded(filepath: str, patterns: List[str], include_self_generated: bool = True) -> bool:
    """
    Check if a file should be excluded based on glob patterns.
    """
    if include_self_generated and is_self_generated(filepath):
        return True

    if not patterns:
        return False

    for pattern in patterns:
        if fnmatch.fnmatch(filepath, pattern):
            return True
        if pattern.endswith('/**'):
            folder = pattern[:-2]
            if filepath.startswith(folder) or filepath.startswith(folder + '/'):
                return True
        if not any(c in pattern for c in '*?['):
            if filepath.startswith(pattern + '/') or filepath == pattern:
                return True

    return False


def parse_exclude_patterns(exclude_str: str) -> List[str]:
    """Parse comma-separated exclude patterns from input."""
    if not exclude_str:
        return []
    patterns = [p.strip() for p in exclude_str.split(',') if p.strip()]
    return patterns